CREATE TABLE IF NOT EXISTS user (
    id PRIMARY KEY INTEGER,
    avatar_url TEXT,
    country_code TEXT,
    default_group TEXT,
    is_active TEXT,
    is_bot TEXT,
    is_deleted TEXT,
    is_online TEXT,
    is_supporter TEXT,
    last_visit INTEGER,
    pm_friends_only TEXT,
    profile_colour INTEGER,
    username TEXT,
    country_name TEXT,
    cover_custom_url TEXT,
    cover_url TEXT,
    cover_id INTEGER,
    groups TEXT,
    osu_id,
    taiko_id,
    fruits_id,
    mania_id,
    team_id
);

CREATE TABLE IF NOT EXISTS osu (
    id PRIMARY KEY INTEGER,
    count_100 INTEGER,
    count_300 INTEGER,
    count_50 INTEGER,
    count_miss INTEGER,
    level_current INTEGER,
    level_progress INTEGER,
    global_rank INTEGER,
    global_rank_exp INTEGER,
    pp NUMERIC,
    pp_exp INTEGER,
    ranked_score INTEGER,
    hit_accuracy NUMERIC,
    play_count INTEGER,
    play_time INTEGER,
    total_score INTEGER,
    total_hits INTEGER,
    maximum_combo INTEGER,
    replays_watched_by_others INTEGER,
    is_ranked TEXT,
    grade_counts_ss INTEGER,
    grade_counts_ssh INTEGER,
    grade_counts_s INTEGER,
    grade_counts_sh INTEGER,
    grade_counts_a INTEGER
);

CREATE TABLE IF NOT EXISTS taiko (
    id PRIMARY KEY INTEGER,
    count_100 INTEGER,
    count_300 INTEGER,
    count_50 INTEGER,
    count_miss INTEGER,
    level_current INTEGER,
    level_progress INTEGER,
    global_rank INTEGER,
    global_rank_exp INTEGER,
    pp NUMERIC,
    pp_exp INTEGER,
    ranked_score INTEGER,
    hit_accuracy NUMERIC,
    play_count INTEGER,
    play_time INTEGER,
    total_score INTEGER,
    total_hits INTEGER,
    maximum_combo INTEGER,
    replays_watched_by_others INTEGER,
    is_ranked TEXT,
    grade_counts_ss INTEGER,
    grade_counts_ssh INTEGER,
    grade_counts_s INTEGER,
    grade_counts_sh INTEGER,
    grade_counts_a INTEGER
);

CREATE TABLE IF NOT EXISTS fruits (
    id PRIMARY KEY INTEGER,
    count_100 INTEGER,
    count_300 INTEGER,
    count_50 INTEGER,
    count_miss INTEGER,
    level_current INTEGER,
    level_progress INTEGER,
    global_rank INTEGER,
    global_rank_exp INTEGER,
    pp NUMERIC,
    pp_exp INTEGER,
    ranked_score INTEGER,
    hit_accuracy NUMERIC,
    play_count INTEGER,
    play_time INTEGER,
    total_score INTEGER,
    total_hits INTEGER,
    maximum_combo INTEGER,
    replays_watched_by_others INTEGER,
    is_ranked TEXT,
    grade_counts_ss INTEGER,
    grade_counts_ssh INTEGER,
    grade_counts_s INTEGER,
    grade_counts_sh INTEGER,
    grade_counts_a INTEGER
);

CREATE TABLE IF NOT EXISTS mania (
    id PRIMARY KEY INTEGER,
    count_100 INTEGER,
    count_300 INTEGER,
    count_50 INTEGER,
    count_miss INTEGER,
    level_current INTEGER,
    level_progress INTEGER,
    global_rank INTEGER,
    global_rank_exp INTEGER,
    pp NUMERIC,
    pp_exp INTEGER,
    ranked_score INTEGER,
    hit_accuracy NUMERIC,
    play_count INTEGER,
    play_time INTEGER,
    total_score INTEGER,
    total_hits INTEGER,
    maximum_combo INTEGER,
    replays_watched_by_others INTEGER,
    is_ranked TEXT,
    grade_counts_ss INTEGER,
    grade_counts_ssh INTEGER,
    grade_counts_s INTEGER,
    grade_counts_sh INTEGER,
    grade_counts_a INTEGER
);

CREATE TABLE IF NOT EXISTS mania_variants (
    id PRIMARY KEY INTEGER,
    mania_id INTEGER,
    mode TEXT,
    variant TEXT,
    country_rank INTEGER,
    global_rank INTEGER,
    pp NUMERIC,
    FOREIGN KEY (mania_id) REFERENCES mania(id)
);

CREATE TABLE IF NOT EXISTS team (
    id PRIMARY KEY INTEGER,
    flag_url TEXT,
    team_id INTEGER,
    name TEXT,
    short_name TEXT
);